/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.admin;

import com.draculatheme.jetbrains.DraculaMeta;
import com.formdev.flatlaf.IntelliJTheme;
import java.awt.Dimension;
import java.awt.Toolkit;
import view.Add_New_User;
import view.UserLogin;

/**
 *
 * @author Pavan Fernando
 */
public class Admin_Home extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Home
     */
    public Admin_Home() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        user_detailsBTN = new javax.swing.JButton();
        add_new_user_BTN = new javax.swing.JButton();
        product_detailsBTN2 = new javax.swing.JButton();
        material_detailsBTN3 = new javax.swing.JButton();
        customer_detailsBTN4 = new javax.swing.JButton();
        logOutBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setText("Admin Controls");

        user_detailsBTN.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        user_detailsBTN.setText("User Details");
        user_detailsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_detailsBTNActionPerformed(evt);
            }
        });

        add_new_user_BTN.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        add_new_user_BTN.setText("Add New User");
        add_new_user_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_new_user_BTNActionPerformed(evt);
            }
        });

        product_detailsBTN2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        product_detailsBTN2.setText("Product Details");
        product_detailsBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_detailsBTN2ActionPerformed(evt);
            }
        });

        material_detailsBTN3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        material_detailsBTN3.setText("Material Details");
        material_detailsBTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                material_detailsBTN3ActionPerformed(evt);
            }
        });

        customer_detailsBTN4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        customer_detailsBTN4.setText("Customer Details");
        customer_detailsBTN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_detailsBTN4ActionPerformed(evt);
            }
        });

        logOutBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logOutBTN.setText("Log Out");
        logOutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(user_detailsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(add_new_user_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(material_detailsBTN3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(customer_detailsBTN4)
                                .addGap(61, 61, 61)
                                .addComponent(product_detailsBTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1)))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logOutBTN)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_detailsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_new_user_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(material_detailsBTN3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product_detailsBTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customer_detailsBTN4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(logOutBTN)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_detailsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_detailsBTNActionPerformed
        this.toBack();
        ShowUserDetails userDetail = new ShowUserDetails();
        userDetail.setVisible(true);
        userDetail.toFront();
    }//GEN-LAST:event_user_detailsBTNActionPerformed

    private void add_new_user_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_new_user_BTNActionPerformed
        this.toBack();
        Add_New_User nuser = new Add_New_User();
        nuser.setVisible(true);
        nuser.toFront();
    }//GEN-LAST:event_add_new_user_BTNActionPerformed

    private void product_detailsBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_detailsBTN2ActionPerformed
        this.toBack();
        ShowProductDetails producDetail = new ShowProductDetails();
        producDetail.setVisible(true);
        producDetail.toFront();
    }//GEN-LAST:event_product_detailsBTN2ActionPerformed

    private void material_detailsBTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_material_detailsBTN3ActionPerformed
        this.toBack();
        ShowRawMaterialDetails materialDetails = new ShowRawMaterialDetails();
        materialDetails.setVisible(true);
        materialDetails.toFront();
    }//GEN-LAST:event_material_detailsBTN3ActionPerformed

    private void customer_detailsBTN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_detailsBTN4ActionPerformed
        this.toBack();
        ShowCustomerDetails cusDetail = new ShowCustomerDetails();
        cusDetail.setVisible(true);
        cusDetail.toFront();
    }//GEN-LAST:event_customer_detailsBTN4ActionPerformed

    private void logOutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBTNActionPerformed
        this.dispose();
        UserLogin obj = new UserLogin();
        obj.setVisible(true);
    }//GEN-LAST:event_logOutBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            IntelliJTheme.setup(DraculaMeta.class.getResourceAsStream("/themes/Dracula.theme.json"));
        } catch (Exception e) {
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_new_user_BTN;
    private javax.swing.JButton customer_detailsBTN4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logOutBTN;
    private javax.swing.JButton material_detailsBTN3;
    private javax.swing.JButton product_detailsBTN2;
    private javax.swing.JButton user_detailsBTN;
    // End of variables declaration//GEN-END:variables
}
