/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.DBConnection;
import model.DBSearch;
import com.draculatheme.jetbrains.DraculaMeta;
import com.formdev.flatlaf.IntelliJTheme;
import controller.OrderController;
import java.sql.*;
import model.DBConnection;
import model.DBSearch;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import controller.MRPController;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import view.sub_Screens.MRP_more_Details_Screen;

/**
 *
 * @author EACMS
 */
public class MRP_Screen extends javax.swing.JFrame {

    /**
     * Creates new form MRP_Screen
     */
    public MRP_Screen() {
        initComponents();

        loadingOrderIDs();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    String nextOrderID = "";
    String selectedProductName = "";
    String produtData[][] = new String[9][3];
    int x = 0;
    String currentDate = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        custName = new javax.swing.JLabel();
        order_date_field = new javax.swing.JLabel();
        cancelBTN = new javax.swing.JButton();
        saveBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        material_table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        orderID = new javax.swing.JComboBox<>();
        saveBTN1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        custName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        custName.setText(".");

        order_date_field.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        order_date_field.setText(".");

        cancelBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBTN.setText("Cancel");
        cancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTNActionPerformed(evt);
            }
        });

        saveBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveBTN.setText("Save");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setText("Material Requirements Planning");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Order ID        :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Order Date :");

        material_table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        material_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Material ID", "Material Name", "Quantity for the Order (kg)"
            }
        ));
        jScrollPane1.setViewportView(material_table);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Customer Name :");

        orderID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        orderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderIDActionPerformed(evt);
            }
        });

        saveBTN1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveBTN1.setText("<<More Details");
        saveBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel1)
                .addGap(0, 203, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)
                        .addComponent(orderID, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(order_date_field, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(custName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(saveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(cancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(saveBTN1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(custName)
                    .addComponent(jLabel2)
                    .addComponent(orderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(order_date_field))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveBTN1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBTN)
                    .addComponent(cancelBTN))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadingOrderIDs() {
        try {
            ResultSet result = new DBSearch().getOrderIDs();
            while (result.next()) {
                String nextOrderID = result.getString(1);
                this.orderID.addItem(nextOrderID);
            }
            DBConnection.closeCon();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }


    private void cancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTNActionPerformed
        this.dispose();
        MRP_Home_Screen mRP_Home_Screen = new MRP_Home_Screen();
        mRP_Home_Screen.setVisible(true);


    }//GEN-LAST:event_cancelBTNActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        try {
            ResultSet result = new DBSearch().get_Material_Details_According_to_OrderId(this.orderID.getSelectedItem().toString());

            while (result.next()) {
                MRPController.insert_data_to_Order_row_material(this.orderID.getSelectedItem().toString(), result.getString(2), result.getString(5), "");
            }

            JOptionPane.showMessageDialog(this, "Details has been added!!");
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_saveBTNActionPerformed

    private void orderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderIDActionPerformed
//clear table data

        setCustomerdetails(this.orderID.getSelectedItem().toString());
        setMaterialDetails(this.orderID.getSelectedItem().toString());
    }//GEN-LAST:event_orderIDActionPerformed

    private void saveBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTN1ActionPerformed
        MRP_more_Details_Screen mRP_more_Details_Screen = new MRP_more_Details_Screen(this.orderID.getSelectedItem().toString());
        //for not to close on close button
        mRP_more_Details_Screen.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        mRP_more_Details_Screen.setVisible(true);
    }//GEN-LAST:event_saveBTN1ActionPerformed

    private void setMaterialDetails(String order_id) {
        try {
            ResultSet result = new DBSearch().get_Material_Details_According_to_OrderId(order_id);
            DefaultTableModel model = (DefaultTableModel) material_table.getModel();
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            }
            while (result.next()) {
                Object[] row = {result.getString(2), result.getString(3), result.getString(5)};
//have to add details to the database
                model.addRow(row);
            }

            DBConnection.closeCon();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

//         set material plan //all details
    private void setFullMaterialDetails(String order_id) {
        try {
            ResultSet result = new DBSearch().get_Material_Details_According_to_OrderId(order_id);
            DefaultTableModel model = (DefaultTableModel) material_table.getModel();
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            }
            while (result.next()) {
                Object[] row = {result.getString(3), result.getString(4), result.getString(9)};

                model.addRow(row);
            }

            DBConnection.closeCon();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    //set customer details and order date
    private void setCustomerdetails(String order_id) {
        try {
            ResultSet result = new DBSearch().get_Customer_Details_From_OrderId(order_id);
            while (result.next()) {
                this.custName.setText(result.getString(4));
                this.order_date_field.setText(result.getString(2));
            }
            DBConnection.closeCon();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MRP_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MRP_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MRP_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MRP_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            IntelliJTheme.setup(DraculaMeta.class.getResourceAsStream("/themes/Dracula.theme.json"));
        } catch (Exception e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MRP_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBTN;
    private javax.swing.JLabel custName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable material_table;
    private javax.swing.JComboBox<String> orderID;
    private javax.swing.JLabel order_date_field;
    private javax.swing.JButton saveBTN;
    private javax.swing.JButton saveBTN1;
    // End of variables declaration//GEN-END:variables
}
