/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.draculatheme.jetbrains.DraculaMeta;
import com.formdev.flatlaf.IntelliJTheme;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Pavan Fernando
 */
public class SalesManagement extends javax.swing.JFrame {

    /**
     * Creates new form SalesManagement
     */
    public SalesManagement() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        orderPlacingBTN = new javax.swing.JButton();
        addNewCustomerBTN = new javax.swing.JButton();
        customerHandlingBTN = new javax.swing.JButton();
        logOutBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setText("Sales Management Department");

        orderPlacingBTN.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        orderPlacingBTN.setText("Order Placing");
        orderPlacingBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderPlacingBTNActionPerformed(evt);
            }
        });

        addNewCustomerBTN.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        addNewCustomerBTN.setText("Add New Customer");
        addNewCustomerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewCustomerBTNActionPerformed(evt);
            }
        });

        customerHandlingBTN.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        customerHandlingBTN.setText("Customer Handling");
        customerHandlingBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerHandlingBTNActionPerformed(evt);
            }
        });

        logOutBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logOutBTN.setText("Log Out");
        logOutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logOutBTN)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(orderPlacingBTN)
                                .addGap(32, 32, 32)
                                .addComponent(customerHandlingBTN)
                                .addGap(28, 28, 28)
                                .addComponent(addNewCustomerBTN)))
                        .addGap(38, 38, 38))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderPlacingBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerHandlingBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewCustomerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(logOutBTN)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderPlacingBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderPlacingBTNActionPerformed
        this.toBack();
        OrderPlaning ordPlaning = new OrderPlaning();
        ordPlaning.setVisible(true);
        ordPlaning.toFront();
    }//GEN-LAST:event_orderPlacingBTNActionPerformed

    private void customerHandlingBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerHandlingBTNActionPerformed
        this.toBack();
        Customer_Details cusDetail = new Customer_Details();
        cusDetail.setVisible(true);
        cusDetail.toFront();
    }//GEN-LAST:event_customerHandlingBTNActionPerformed

    private void addNewCustomerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewCustomerBTNActionPerformed
        this.toBack();
        AddNewCustomer newCus = new AddNewCustomer();
        newCus.setVisible(true);
        newCus.toFront();
    }//GEN-LAST:event_addNewCustomerBTNActionPerformed

    private void logOutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBTNActionPerformed
        this.dispose();
        UserLogin obj = new UserLogin();
        obj.setVisible(true);
    }//GEN-LAST:event_logOutBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            IntelliJTheme.setup(DraculaMeta.class.getResourceAsStream("/themes/Dracula.theme.json"));
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewCustomerBTN;
    private javax.swing.JButton customerHandlingBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logOutBTN;
    private javax.swing.JButton logOutBTN1;
    private javax.swing.JButton orderPlacingBTN;
    // End of variables declaration//GEN-END:variables
}
