/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.draculatheme.jetbrains.DraculaMeta;
import com.formdev.flatlaf.IntelliJTheme;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Pavan Fernando
 */
public class Warehouse_Home extends javax.swing.JFrame {

    /**
     * Creates new form Warehouse_Home
     */
    public Warehouse_Home() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        issuingRawMaterialsBTN = new javax.swing.JButton();
        ReceievedRawMaterialsBTN = new javax.swing.JButton();
        logOutBTN1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setText("Werehouse Department");

        issuingRawMaterialsBTN.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        issuingRawMaterialsBTN.setText("Issuing Raw Materials");
        issuingRawMaterialsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuingRawMaterialsBTNActionPerformed(evt);
            }
        });

        ReceievedRawMaterialsBTN.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        ReceievedRawMaterialsBTN.setText("Recieved Raw Materials");
        ReceievedRawMaterialsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceievedRawMaterialsBTNActionPerformed(evt);
            }
        });

        logOutBTN1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logOutBTN1.setText("Log Out");
        logOutBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBTN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(221, 221, 221))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logOutBTN1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(issuingRawMaterialsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(ReceievedRawMaterialsBTN)))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issuingRawMaterialsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReceievedRawMaterialsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(logOutBTN1)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void issuingRawMaterialsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuingRawMaterialsBTNActionPerformed
                this.toBack();
                Issuing_Raw_materials objOne = new Issuing_Raw_materials();
                objOne.setVisible(true);
                objOne.toFront();
    }//GEN-LAST:event_issuingRawMaterialsBTNActionPerformed

    private void ReceievedRawMaterialsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceievedRawMaterialsBTNActionPerformed
                this.toBack();
                Received_Raw_Materials objTwo = new Received_Raw_Materials();
                objTwo.setVisible(true);
                objTwo.toFront();
    }//GEN-LAST:event_ReceievedRawMaterialsBTNActionPerformed

    private void logOutBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBTN1ActionPerformed
        this.dispose();
        UserLogin obj = new UserLogin();
        obj.setVisible(true);
    }//GEN-LAST:event_logOutBTN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      try {
            IntelliJTheme.setup(DraculaMeta.class.getResourceAsStream("/themes/Dracula.theme.json"));
        } catch (Exception e) {
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Warehouse_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReceievedRawMaterialsBTN;
    private javax.swing.JButton issuingRawMaterialsBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logOutBTN;
    private javax.swing.JButton logOutBTN1;
    // End of variables declaration//GEN-END:variables
}
